[package]
name = "ai_sdk"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
reqwest = { version = "0.12.7", default-features = false, features = ["rustls-tls", "json"] }
serde = { workspace = true}

[dev-dependencies]
tokio = { workspace = true}
