fail_fast: false
default_install_hook_types: [pre-commit, commit-msg]
default_stages: [commit, manual]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        description: Format files with rustfmt.
        entry: bash -c 'for dir in chat chatapp/src-tauri; do (cd $dir && cargo fmt -- --check); done'
        language: rust
        files: \.rs$
        args: []
      - id: cargo-deny
        name: cargo deny check
        description: Check cargo dependencies
        entry: bash -c 'for dir in chat chatapp/src-tauri; do (cd $dir && cargo deny check -d); done'
        language: rust
        files: \.rs$
        args: []
      - id: typos
        name: typos
        description: check typo
        entry: bash -c 'typos'
        language: rust
        files: \.*$
        pass_filenames: false
      - id: cargo-check
        name: cargo check
        description: Check the package for errors.
        entry: bash -c 'for dir in chat chatapp/src-tauri; do (cd $dir && cargo check --all); done'
        language: rust
        files: \.rs$
        pass_filenames: false
      - id: cargo-clippy
        name: cargo clippy
        description: Lint rust sources
        entry: bash -c 'for dir in chat chatapp/src-tauri; do (cd $dir && cargo clippy --all-targets --all-features --tests --benches -- -D warnings); done'
        language: rust
        files: \.rs$
        pass_filenames: false
      - id: cargo-test
        name: cargo test
        description: unit test for the project
        entry: bash -c 'for dir in chat chatapp/src-tauri; do (cd $dir && cargo nextest run --all-features -- --include-ignored); done'
        language: rust
        files: \.rs$
        pass_filenames: false
